# Generated by Django 4.2.27 on 2026-07-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_brand_slug_alter_product_slug"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "عنصر السلة",
                "verbose_name_plural": "عناصر السلة",
            },
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "variant")},
        ),
    ]
