# Generated by Django 4.2.27 on 2026-01-31 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="العنوان")),
                (
                    "image",
                    models.ImageField(upload_to="cms/banners/", verbose_name="الصورة"),
                ),
                ("link", models.CharField(max_length=200, verbose_name="الرابط")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("home_top", "الرئيسية - أعلى"),
                            ("home_middle", "الرئيسية - وسط"),
                            ("products_top", "المنتجات - أعلى"),
                            ("sidebar", "الشريط الجانبي"),
                        ],
                        max_length=20,
                        verbose_name="المكان",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "بانر",
                "verbose_name_plural": "البانرات",
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="العنوان")),
                (
                    "subtitle",
                    models.TextField(max_length=200, verbose_name="العنوان الفرعي"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="cms/slides/", verbose_name="صورة العرض"
                    ),
                ),
                (
                    "image_mobile",
                    models.ImageField(
                        blank=True,
                        upload_to="cms/slides/mobile/",
                        verbose_name="صورة الجوال (اختياري)",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(max_length=50, verbose_name="نص الزر"),
                ),
                (
                    "button_link",
                    models.CharField(max_length=200, verbose_name="رابط الزر"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="بداية العرض"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="نهاية العرض"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                        verbose_name="ارتباط بمنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "سلايدر العرض",
                "verbose_name_plural": "سلايدرات العرض",
                "ordering": ["order"],
            },
        ),
    ]
