# Generated by Django 4.2.24 on 2026-02-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(
                        default="Almustafa's Perfume",
                        max_length=100,
                        verbose_name="اسم المتجر",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="هاتف التواصل"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الواتساب"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                (
                    "facebook_link",
                    models.URLField(blank=True, verbose_name="رابط فيسبوك"),
                ),
                (
                    "instagram_link",
                    models.URLField(blank=True, verbose_name="رابط انستغرام"),
                ),
                (
                    "tiktok_link",
                    models.URLField(blank=True, verbose_name="رابط تيك توك"),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=25.0,
                        max_digits=10,
                        verbose_name="تكلفة الشحن (ثابتة)",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات المتجر",
                "verbose_name_plural": "إعدادات المتجر",
            },
        ),
    ]
