# Generated by Django 4.2.24 on 2026-02-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_storesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storesettings",
            name="shipping_cost",
        ),
    ]
