# Generated by Django 4.2.27 on 2026-02-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_remove_storesettings_shipping_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="button_link",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="رابط الزر"
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="button_text",
            field=models.CharField(blank=True, max_length=50, verbose_name="نص الزر"),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="subtitle",
            field=models.TextField(
                blank=True, max_length=200, verbose_name="العنوان الفرعي"
            ),
        ),
    ]
