# Generated by Django 4.2.24 on 2026-02-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_alter_heroslide_button_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("ramadan", "قسم رمضان/المناسبات"),
                            ("features", "مميزات المتجر"),
                            ("best_sellers", "الأكثر مبيعاً (سلايدر)"),
                            ("featured_products", "العطور المميزة"),
                            ("banner", "البانر الإعلاني"),
                            ("vision", "الرؤية وفلسفة العطور"),
                            ("categories", "تسوق حسب الفئات"),
                            ("stats", "إحصائيات النجاح"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="القسم",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=100, verbose_name="عنوان القسم (داخلي)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ظهور القسم"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "محتوى الصفحة الرئيسية (HPC)",
                "verbose_name_plural": "محتويات الصفحة الرئيسية (HPC)",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="heroslide",
            name="description_ar",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="الوصف"
            ),
        ),
    ]
