# Generated by Django 4.2.24 on 2026-02-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_homepagesection_heroslide_description_ar"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagesection",
            name="content",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="محتوى القسم"
            ),
        ),
    ]
