# Generated by Django 4.2.27 on 2026-03-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_homepagesection_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="top_banner_is_active",
            field=models.BooleanField(default=True, verbose_name="تفعيل البانر العلوي"),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="top_banner_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="نص البانر العلوي"
            ),
        ),
    ]
