# Generated by Django 4.2.27 on 2026-07-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_storesettings_top_banner_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepagesection",
            options={
                "ordering": ["order"],
                "verbose_name": "قسم الصفحة الرئيسية",
                "verbose_name_plural": "أقسام الصفحة الرئيسية",
            },
        ),
        migrations.AddField(
            model_name="storesettings",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=25.0,
                max_digits=10,
                verbose_name="تكلفة الشحن",
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="button_link",
            field=models.CharField(max_length=200, verbose_name="رابط الزر"),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="button_text",
            field=models.CharField(max_length=50, verbose_name="نص الزر"),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="description_ar",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="الوصف بالعربية"
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="subtitle",
            field=models.TextField(max_length=200, verbose_name="العنوان الفرعي"),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="content",
            field=models.JSONField(blank=True, null=True, verbose_name="المحتوى"),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="key",
            field=models.CharField(max_length=50, unique=True, verbose_name="المعرف"),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="title_ar",
            field=models.CharField(max_length=200, verbose_name="العنوان بالعربية"),
        ),
    ]
