# Generated by Django 4.2.27 on 2026-07-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_alter_homepagesection_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={
                "ordering": ["id"],
                "verbose_name": "بانر",
                "verbose_name_plural": "البانرات",
            },
        ),
    ]
