# Generated by Django 4.2.27 on 2026-01-31 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("crm", "0001_initial"),
        ("marketing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم الطلب"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="اسم العميل"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="رقم الهاتف"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="المدينة")),
                ("area", models.CharField(max_length=100, verbose_name="المنطقة")),
                ("address", models.TextField(verbose_name="العنوان")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المجموع الفرعي"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="قيمة الخصم",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="تكلفة التوصيل"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="الإجمالي"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "في الانتظار"),
                            ("confirmed", "مؤكد"),
                            ("processing", "قيد التجهيز"),
                            ("shipped", "تم الشحن"),
                            ("delivered", "تم التوصيل"),
                            ("cancelled", "ملغي"),
                            ("returned", "مرتجع"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة الطلب",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات العميل")),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الإدارة"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموظف المسؤول",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketing.coupon",
                        verbose_name="الكوبون",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="crm.customerprofile",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "الطلب",
                "verbose_name_plural": "الطلبات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "في الانتظار"),
                            ("confirmed", "مؤكد"),
                            ("processing", "قيد التجهيز"),
                            ("shipped", "تم الشحن"),
                            ("delivered", "تم التوصيل"),
                            ("cancelled", "ملغي"),
                            ("returned", "مرتجع"),
                        ],
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تغيير بواسطة",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تاريخ حالة الطلب",
                "verbose_name_plural": "تاريخ حالات الطلب",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="اسم المنتج"),
                ),
                (
                    "variant_size",
                    models.PositiveIntegerField(verbose_name="الحجم (مل)"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="الكمية"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="الإجمالي"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.productvariant",
                        verbose_name="العبوة",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر الطلب",
                "verbose_name_plural": "عناصر الطلب",
            },
        ),
    ]
