# Generated by Django 4.2.24 on 2026-01-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="birth_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="يوم الميلاد"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="birth_month",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="شهر الميلاد"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="birth_year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="سنة الميلاد"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="location_details",
            field=models.TextField(
                blank=True, verbose_name="تفاصيل المكان أو أقرب علامة"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(verbose_name="العنوان بالتفصيل"),
        ),
    ]
