# Generated by Django 4.2.24 on 2026-02-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_birth_day_order_birth_month_order_birth_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="variant_size",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="الحجم (مل)"
            ),
        ),
    ]
