# Generated by Django 4.2.27 on 2026-07-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="backups/")),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "جاري الإنشاء"),
                            ("ready", "جاهز"),
                            ("failed", "فشل"),
                            ("restoring", "جاري الاستعادة"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
