# Generated by Django 4.2.27 on 2026-01-31 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="اسم التاج")),
                (
                    "color",
                    models.CharField(
                        default="#C5A572", max_length=7, verbose_name="اللون"
                    ),
                ),
            ],
            options={
                "verbose_name": "تاجات العملاء",
                "verbose_name_plural": "تاجات العملاء",
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم العميل")),
                (
                    "phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الواتساب"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المنطقة"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="العنوان بالتفصيل"),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي الطلبات"
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="إجمالي الإنفاق",
                    ),
                ),
                (
                    "avg_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="متوسط قيمة الطلب",
                    ),
                ),
                (
                    "last_order_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ آخر طلب"
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("regular", "متكرر"),
                            ("vip", "VIP"),
                            ("inactive", "خامل"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="التصنيف",
                    ),
                ),
                (
                    "preferred_gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "رجالي"), ("F", "نسائي"), ("U", "للجنسين")],
                        max_length=1,
                        verbose_name="النوع المفضل",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "favorite_brands",
                    models.ManyToManyField(
                        blank=True, to="products.brand", verbose_name="الماركات المفضلة"
                    ),
                ),
                (
                    "favorite_families",
                    models.ManyToManyField(
                        blank=True,
                        to="products.fragrancefamily",
                        verbose_name="العائلات الوعطرية المفضلة",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="crm.customertag", verbose_name="التاجات"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف العميل",
                "verbose_name_plural": "ملفات العملاء",
            },
        ),
        migrations.CreateModel(
            name="CustomerInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "مكالمة"),
                            ("whatsapp", "واتساب"),
                            ("email", "بريد إلكتروني"),
                            ("note", "ملاحظة"),
                            ("complaint", "شكوى"),
                            ("followup", "متابعة"),
                        ],
                        max_length=15,
                        verbose_name="نوع التواصل",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="الموضوع")),
                ("content", models.TextField(verbose_name="المحتوى")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm.customerprofile",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "تواصل مع عميل",
                "verbose_name_plural": "سجل التواصل مع العملاء",
            },
        ),
    ]
