# Generated by Django 4.2.24 on 2026-01-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="birth_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="يوم الميلاد"
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="birth_month",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="شهر الميلاد"
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="birth_year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="سنة الميلاد"
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="location_details",
            field=models.TextField(
                blank=True, verbose_name="تفاصيل المكان أو أقرب علامة"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="رقم الهاتف"),
        ),
        migrations.AlterUniqueTogether(
            name="customerprofile",
            unique_together={("name", "birth_day", "birth_month", "birth_year")},
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="birth_date",
        ),
    ]
