# Generated by Django 4.2.27 on 2026-02-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_customerprofile_birth_day_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ملف العميل",
                "verbose_name_plural": "ملفات العملاء",
            },
        ),
        migrations.AlterUniqueTogether(
            name="customerprofile",
            unique_together={("name", "phone")},
        ),
    ]
