# Generated by Django 4.2.27 on 2026-01-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود الخصم"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "نسبة مئوية"), ("fixed", "مبلغ ثابت")],
                        max_length=15,
                        verbose_name="نوع الخصم",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قيمة الخصم"
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الحد الأدنى للطلب",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="أقصى قيمة للخصم",
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="حد الاستخدام"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مرات الاستخدام"
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="صالح من")),
                ("valid_to", models.DateTimeField(verbose_name="صالح إلى")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "كوبون الخصم",
                "verbose_name_plural": "كوبونات الخصم",
            },
        ),
    ]
