# Generated by Django 4.2.24 on 2026-02-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={
                "ordering": ["code"],
                "verbose_name": "كوبون الخصم",
                "verbose_name_plural": "كوبونات الخصم",
            },
        ),
    ]
