# Generated by Django 4.2.27 on 2026-01-31 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم بالعربية"),
                ),
                ("logo", models.ImageField(upload_to="brands/", verbose_name="الشعار")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "الماركة",
                "verbose_name_plural": "الماركات",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم بالعربية"),
                ),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
                (
                    "image",
                    models.ImageField(upload_to="categories/", verbose_name="الصورة"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "الفئة",
                "verbose_name_plural": "الفئات",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FragranceFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم بالعربية"),
                ),
                ("icon", models.CharField(max_length=50, verbose_name="الأيقونة")),
                ("color", models.CharField(max_length=7, verbose_name="اللون")),
            ],
            options={
                "verbose_name": "العائلة العطرية",
                "verbose_name_plural": "العائلات العطرية",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="الاسم بالعربية"),
                ),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "story",
                    models.TextField(
                        help_text="القصة العطرية", verbose_name="القصة العطرية"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "رجالي"), ("F", "نسائي"), ("U", "للجنسين")],
                        max_length=1,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "concentration",
                    models.CharField(
                        choices=[
                            ("EDT", "Eau de Toilette"),
                            ("EDP", "Eau de Parfum"),
                            ("P", "Parfum"),
                        ],
                        max_length=3,
                        verbose_name="التركيز",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="products/", verbose_name="الصورة الرئيسية"
                    ),
                ),
                (
                    "longevity_rating",
                    models.PositiveIntegerField(default=5, verbose_name="تقييم الثبات"),
                ),
                (
                    "sillage_rating",
                    models.PositiveIntegerField(
                        default=5, verbose_name="تقييم الفوحان"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مميز"),
                ),
                (
                    "is_bestseller",
                    models.BooleanField(default=False, verbose_name="الأكثر مبيعاً"),
                ),
                ("is_new", models.BooleanField(default=False, verbose_name="جديد")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المشاهدات"
                    ),
                ),
                (
                    "sales_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد المبيعات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.brand",
                        verbose_name="الماركة",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "fragrance_families",
                    models.ManyToManyField(
                        to="products.fragrancefamily", verbose_name="العائلات العطرية"
                    ),
                ),
            ],
            options={
                "verbose_name": "المنتج",
                "verbose_name_plural": "المنتجات",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_ml", models.PositiveIntegerField(verbose_name="الحجم (مل)")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر الأصلي"
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="سعر العرض",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="للتقارير الداخلية",
                        max_digits=10,
                        verbose_name="سعر التكلفة",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الكمية في المخزن"
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=5, verbose_name="حد المخزون المنخفض"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رمز SKU"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الباركود"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="variants/",
                        verbose_name="صورة خاصة للعبوة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "عبوة المنتج",
                "verbose_name_plural": "عبوات المنتجات",
            },
        ),
        migrations.CreateModel(
            name="ProductNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("top", "افتتاحية"),
                            ("heart", "قلب"),
                            ("base", "قاعدية"),
                        ],
                        max_length=10,
                        verbose_name="نوع النوتة",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=100, verbose_name="اسم المكون بالعربية"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الأيقونة"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوتة العطر",
                "verbose_name_plural": "نوتات العطور",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/", verbose_name="الصورة"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نص بديل"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة إضافية",
                "verbose_name_plural": "صور إضافية",
                "ordering": ["order"],
            },
        ),
    ]
