# Generated by Django 4.2.24 on 2026-02-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="الوصف"),
        ),
        migrations.AlterField(
            model_name="product",
            name="fragrance_families",
            field=models.ManyToManyField(
                blank=True,
                to="products.fragrancefamily",
                verbose_name="العائلات العطرية",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("men", "رجالي"), ("women", "نسائي"), ("unisex", "للجنسين")],
                max_length=10,
                verbose_name="الجنس",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="story",
            field=models.TextField(
                blank=True,
                default="",
                help_text="القصة العطرية",
                verbose_name="القصة العطرية",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="للتقارير الداخلية",
                max_digits=10,
                null=True,
                verbose_name="سعر التكلفة",
            ),
        ),
    ]
