# Generated by Django 4.2.24 on 2026-02-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_brand_slug_alter_brand_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["name_ar"],
                "verbose_name": "الماركة",
                "verbose_name_plural": "الماركات",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "المنتج",
                "verbose_name_plural": "المنتجات",
            },
        ),
    ]
