# Generated by Django 4.2.24 on 2026-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_brand_options_alter_product_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="concentration",
        ),
        migrations.RemoveField(
            model_name="product",
            name="longevity_rating",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sillage_rating",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(to="products.category", verbose_name="الفئات"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size_ml",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="الحجم (مل)"
            ),
        ),
    ]
