# Generated by Django 4.2.24 on 2026-02-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0005_remove_product_category_remove_product_concentration_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="اسم العبوة"
            ),
        ),
    ]
