# Generated by Django 4.2.24 on 2026-02-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productvariant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="occasion",
            field=models.TextField(
                blank=True,
                help_text="ex: ليلي, حفلات, كلاسيكي",
                verbose_name="مناسب لـ",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="vibe",
            field=models.TextField(
                blank=True, help_text="ex: قوي, دافئ, رجولي", verbose_name="مزاج العطر"
            ),
        ),
    ]
