# Generated by Django 4.2.27 on 2026-03-03 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_occasion_product_vibe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.brand",
                verbose_name="الماركة",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="products.category", verbose_name="الفئات"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("men", "رجالي"), ("women", "نسائي"), ("unisex", "للجنسين")],
                default="unisex",
                max_length=10,
                verbose_name="الجنس",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="الصورة الرئيسية",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="رمز SKU"
            ),
        ),
    ]
