# Generated by Django 4.2.27 on 2026-07-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, unique=True, verbose_name="المعرف"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
