# Generated by Django 4.2.27 on 2026-07-24 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_brand_slug_alter_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
