# Generated by Django 4.2.27 on 2026-07-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_remove_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bulk_ml_stock",
            field=models.PositiveIntegerField(
                default=0, verbose_name="مخزون السائل الإجمالي (مل)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_type",
            field=models.CharField(
                choices=[("unit", "بالقطع"), ("bulk_ml", "بالسائل - مل")],
                default="unit",
                max_length=10,
                verbose_name="نوع إدارة المخزون",
            ),
        ),
    ]
