# Generated by Django 4.2.27 on 2026-07-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_product_bulk_ml_stock_product_stock_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_calculated_from_ml",
            field=models.BooleanField(
                default=True, verbose_name="حساب تلقائي من مخزون السائل"
            ),
        ),
    ]
